services:

  db:
    restart: "no"

  app:
    restart: "no"
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app/backend
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild
        - path: ./frontend/src
          action: rebuild
        - path: ./frontend/package.json
          action: rebuild
    volumes:
      - ./backend/htmlcov:/app/backend/htmlcov
