// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ComputerCreate = {
    name: string;
    mac_address: string;
    ip_address?: (string | null);
    description?: (string | null);
};

export type ComputerPublic = {
    name: string;
    mac_address: string;
    ip_address?: (string | null);
    description?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type ComputersPublic = {
    data: Array<ComputerPublic>;
    count: number;
};

export type ComputerUpdate = {
    name?: (string | null);
    mac_address?: (string | null);
    ip_address?: (string | null);
    description?: (string | null);
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    username: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    username: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    username: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    username?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    username?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type ComputersReadComputersData = {
    limit?: number;
    skip?: number;
};

export type ComputersReadComputersResponse = (ComputersPublic);

export type ComputersCreateComputerData = {
    requestBody: ComputerCreate;
};

export type ComputersCreateComputerResponse = (ComputerPublic);

export type ComputersReadComputerData = {
    id: string;
};

export type ComputersReadComputerResponse = (ComputerPublic);

export type ComputersUpdateComputerData = {
    id: string;
    requestBody: ComputerUpdate;
};

export type ComputersUpdateComputerResponse = (ComputerPublic);

export type ComputersDeleteComputerData = {
    id: string;
};

export type ComputersDeleteComputerResponse = (Message);

export type ComputersWakeComputerData = {
    id: string;
};

export type ComputersWakeComputerResponse = (Message);

export type AccessPointPublic = {
    name: string;
    description?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type AccessPointsPublic = {
    data: Array<AccessPointPublic>;
    count: number;
};

export type AccessPointCreate = {
    name: string;
    description?: (string | null);
};

export type AccessPointUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type AccessGroupPublic = {
    name: string;
    description?: (string | null);
    id: string;
    created_at?: (string | null);
    access_point_ids: Array<string>;
};

export type AccessGroupsPublic = {
    data: Array<AccessGroupPublic>;
    count: number;
};

export type AccessGroupCreate = {
    name: string;
    description?: (string | null);
};

export type AccessGroupUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type AccessCardPublic = {
    uid: string;
    label: string;
    is_active: boolean;
    user_id?: (string | null);
    id: string;
    created_at?: (string | null);
    access_point_ids: Array<string>;
    group_ids: Array<string>;
};

export type AccessCardsPublic = {
    data: Array<AccessCardPublic>;
    count: number;
};

export type AccessCardCreate = {
    uid: string;
    label: string;
    is_active?: boolean;
    user_id?: (string | null);
};

export type AccessCardUpdate = {
    uid?: (string | null);
    label?: (string | null);
    is_active?: (boolean | null);
    user_id?: (string | null);
};

// Access service request/response types

export type AccessListCardsData = {
    skip?: number;
    limit?: number;
};

export type AccessListCardsResponse = (AccessCardsPublic);

export type AccessCreateCardData = {
    requestBody: AccessCardCreate;
};

export type AccessCreateCardResponse = (AccessCardPublic);

export type AccessUpdateCardData = {
    cardId: string;
    requestBody: AccessCardUpdate;
};

export type AccessUpdateCardResponse = (AccessCardPublic);

export type AccessDeleteCardData = {
    cardId: string;
};

export type AccessDeleteCardResponse = (Message);

export type AccessAddCardPointData = {
    cardId: string;
    pointId: string;
};

export type AccessAddCardPointResponse = (AccessCardPublic);

export type AccessRemoveCardPointData = {
    cardId: string;
    pointId: string;
};

export type AccessRemoveCardPointResponse = (AccessCardPublic);

export type AccessAddCardGroupData = {
    cardId: string;
    groupId: string;
};

export type AccessAddCardGroupResponse = (AccessCardPublic);

export type AccessRemoveCardGroupData = {
    cardId: string;
    groupId: string;
};

export type AccessRemoveCardGroupResponse = (AccessCardPublic);

export type AccessListGroupsData = {
    skip?: number;
    limit?: number;
};

export type AccessListGroupsResponse = (AccessGroupsPublic);

export type AccessCreateGroupData = {
    requestBody: AccessGroupCreate;
};

export type AccessCreateGroupResponse = (AccessGroupPublic);

export type AccessUpdateGroupData = {
    groupId: string;
    requestBody: AccessGroupUpdate;
};

export type AccessUpdateGroupResponse = (AccessGroupPublic);

export type AccessDeleteGroupData = {
    groupId: string;
};

export type AccessDeleteGroupResponse = (Message);

export type AccessAddGroupPointData = {
    groupId: string;
    pointId: string;
};

export type AccessAddGroupPointResponse = (AccessGroupPublic);

export type AccessRemoveGroupPointData = {
    groupId: string;
    pointId: string;
};

export type AccessRemoveGroupPointResponse = (AccessGroupPublic);

export type AccessListPointsData = {
    skip?: number;
    limit?: number;
};

export type AccessListPointsResponse = (AccessPointsPublic);

export type AccessCreatePointData = {
    requestBody: AccessPointCreate;
};

export type AccessCreatePointResponse = (AccessPointPublic);

export type AccessUpdatePointData = {
    pointId: string;
    requestBody: AccessPointUpdate;
};

export type AccessUpdatePointResponse = (AccessPointPublic);

export type AccessDeletePointData = {
    pointId: string;
};

export type AccessDeletePointResponse = (Message);
